model convex_qp.mod;
data convex_qp.dat;

# General Options
option show_stats 3;
option presolve 16;
option presolve_eps 0.01;
option solution_precision 13;
option display_1col 1000;
option display_width 1000;
option display_precision 0;
option presolve_warnings -1;

# Solver Options
option conopt_options "outlev=3 timing=3 errlim=10000 Rtnwmi=1e-5 Rtnwma=1e-3";
option ipopt_options "halt_on_ampl_error yes";
option snopt_options "outlev=3";
option knitro_options "outlev=3 ms_enable=0";

let S := 3;
let T := 3;

objective OBJ;

option solver cplex;

solve;
