model "convex_qp_s3_t3.gbd.modr";
model "convex_qp_s3_t3.gbd.modm";
model "convex_qp_s3_t3.gbd.modrsl";
data convex_qp.dat;
option show_stats 3;
option presolve 16;
option presolve_eps 0.01;
option solution_precision 13;
option display_1col 1000;
option display_width 1000;
option display_precision 0;
option presolve_warnings -1;
option conopt_options "outlev=3 timing=3 errlim=10000 Rtnwmi=1e-5 Rtnwma=1e-3";
option ipopt_options "halt_on_ampl_error yes";
option snopt_options "outlev=3";
option knitro_options "outlev=3 ms_enable=0";
let S := 3;
let T := 3;
objective OBJ;
option solver cplex;
problem PrimalSubproblem {s in SCENARIOS, t in TIMEPERIODS}:
	{r in RAW_MATERIALS} INLET[r,t,s],
	{m in MATERIALS} NODE[m,t,s],
	{(l0,l1) in LINKAGES} ARC[l0,l1,t,s],
	PROFIT[t,s],
	OBJ_SUB_PrimalSubproblem[t,s],
	{p in PRODUCTS} PROD_FLOW_RATE[p,t,s],
	{p in PRODUCTS} MIN_PRODUCTION[p,t,s],
	{p in PRODUCTS} PROD_DEMAND[p,t,s],
	{q in QUALITIES, p in PRODUCTS} QUALITY_BLENDING_RULE_MIN[q,p,t,s],
	{q in QUALITIES, p in PRODUCTS} QUALITY_BLENDING_RULE_MAX[q,p,t,s],
	{r in RAW_MATERIALS} NON_ANT[r,t,s],
	{r in RAW_MATERIALS} INLET_FLOW_RATE[r,t,s],
	{r in RAW_MATERIALS} RAW_MAT_FLOW_RATE[r,t,s],
	PROFIT_CALC[t,s]
;
problem PrimalSubproblem_FBL {s in SCENARIOS, t in TIMEPERIODS}:
	{r in RAW_MATERIALS} INLET[r,t,s],
	{m in MATERIALS} NODE[m,t,s],
	{(l0,l1) in LINKAGES} ARC[l0,l1,t,s],
	PROFIT[t,s],
	{p in PRODUCTS} MIN_PRODUCTION_SL[p,t,s],
	{p in PRODUCTS} PROD_DEMAND_SL[p,t,s],
	{q in QUALITIES, p in PRODUCTS} QUALITY_BLENDING_RULE_MIN_SL[q,p,t,s],
	{q in QUALITIES, p in PRODUCTS} QUALITY_BLENDING_RULE_MAX_SL[q,p,t,s],
	FBL_OBJ_PrimalSubproblem[s,t],
	{p in PRODUCTS} PROD_FLOW_RATE[p,t,s],
	{p in PRODUCTS} MIN_PRODUCTION_F[p,t,s],
	{p in PRODUCTS} PROD_DEMAND_F[p,t,s],
	{q in QUALITIES, p in PRODUCTS} QUALITY_BLENDING_RULE_MIN_F[q,p,t,s],
	{q in QUALITIES, p in PRODUCTS} QUALITY_BLENDING_RULE_MAX_F[q,p,t,s],
	{r in RAW_MATERIALS} NON_ANT[r,t,s],
	{r in RAW_MATERIALS} INLET_FLOW_RATE[r,t,s],
	{r in RAW_MATERIALS} RAW_MAT_FLOW_RATE[r,t,s],
	PROFIT_CALC[t,s]
;
problem Master:
	{m in MATERIALS, t in TIMEPERIODS, s in SCENARIOS: (m,t,s) in {r1 in RAW_MATERIALS, t1 in TIMEPERIODS, s1 in SCENARIOS}} NODE[m,t,s],
	ETA,
	{s in SCENARIOS, t in TIMEPERIODS, ct in CUTS} GBD_F[s,t,ct],
	{r in RAW_MATERIALS, t in TIMEPERIODS, s in SCENARIOS, ct in CUTS} GBD_G_0[r,t,s,ct],
	{r in RAW_MATERIALS, t in TIMEPERIODS, s in SCENARIOS, ct in CUTS} GBD_G_1[r,t,s,ct],
	{t in TIMEPERIODS, s in SCENARIOS, ct in CUTS} GBD_G_2[t,s,ct],
	MASTER_OBJ,
	{r in RAW_MATERIALS, t in TIMEPERIODS, s in SCENARIOS} NON_ANT2[r,t,s],
	{ct in CUTS: IS_FEASIBLE[ct] == 1} GBD_OPT_CUT[ct],
	{ct in CUTS: IS_FEASIBLE[ct] == 0} GBD_FBL_CUT[ct],
	ETA_BOUNDS
;