model "convex_qp_s3_t3.origin.modr";
data convex_qp.dat;
option show_stats 3;
option presolve 16;
option presolve_eps 0.01;
option solution_precision 13;
option display_1col 1000;
option display_width 1000;
option display_precision 0;
option presolve_warnings -1;
option conopt_options "outlev=3 timing=3 errlim=10000 Rtnwmi=1e-5 Rtnwma=1e-3";
option ipopt_options "halt_on_ampl_error yes";
option snopt_options "outlev=3";
option knitro_options "outlev=3 ms_enable=0";
let S := 3;
let T := 3;
objective OBJ;
option solver cplex;
problem PrimalSubproblem {s in SCENARIOS, t in TIMEPERIODS}:
	{r in RAW_MATERIALS} INLET[r,t,s],
	{m in MATERIALS} NODE[m,t,s],
	{(l0,l1) in LINKAGES} ARC[l0,l1,t,s],
	PROFIT[t,s],
	OBJ_SUB_PrimalSubproblem[t,s],
	{r in RAW_MATERIALS} INLET_FLOW_RATE[r,t,s],
	{r in RAW_MATERIALS} RAW_MAT_FLOW_RATE[r,t,s],
	{p in PRODUCTS} PROD_FLOW_RATE[p,t,s],
	{p in PRODUCTS} MIN_PRODUCTION[p,t,s],
	{p in PRODUCTS} PROD_DEMAND[p,t,s],
	{q in QUALITIES, p in PRODUCTS} QUALITY_BLENDING_RULE_MIN[q,p,t,s],
	{q in QUALITIES, p in PRODUCTS} QUALITY_BLENDING_RULE_MAX[q,p,t,s],
	PROFIT_CALC[t,s],
	{r in RAW_MATERIALS} NON_ANT[r,t,s],
	{r in RAW_MATERIALS} NON_ANT2[r,t,s]
;