model "decomp.modr";
model "decomp.gbd.modm";
model "decomp.gbd.modrsl";
data decomp.dat;
option show_stats 3;
option presolve 16;
option presolve_eps 0.01;
option solution_precision 13;
option display_1col 1000;
option display_width 1000;
option display_precision 0;
option presolve_warnings -1;
option conopt_options "outlev=3 timing=3 errlim=10000 Rtnwmi=1e-5 Rtnwma=1e-3";
option ipopt_options "halt_on_ampl_error yes";
option snopt_options "outlev=3";
option knitro_options "outlev=3 ms_enable=0";
objective OBJ;
option solver cplex;
problem PrimalSubproblem {s in SCENARIOS}:
	{r in RAW_MATERIALS, t in TIMEPERIODS} INLET[r,t,s],
	{m in MATERIALS, t in TIMEPERIODS} NODE[m,t,s],
	{(l0,l1) in LINKAGES, t in TIMEPERIODS} ARC[l0,l1,t,s],
	{t in TIMEPERIODS} PROFIT[t,s],
	OBJ_SUB_PrimalSubproblem[s],
	{r in RAW_MATERIALS, t in TIMEPERIODS} RAW_MAT_FLOW_RATE[r,t,s],
	{p in PRODUCTS, t in TIMEPERIODS} PROD_FLOW_RATE[p,t,s],
	{p in PRODUCTS, t in TIMEPERIODS} MIN_PRODUCTION[p,t,s],
	{p in PRODUCTS, t in TIMEPERIODS} PROD_DEMAND[p,t,s],
	{q in QUALITIES, p in PRODUCTS, t in TIMEPERIODS} QUALITY_BLENDING_RULE_MIN[q,p,t,s],
	{q in QUALITIES, p in PRODUCTS, t in TIMEPERIODS} QUALITY_BLENDING_RULE_MAX[q,p,t,s],
	{t in TIMEPERIODS} PROFIT_CALC[t,s],
	{r in RAW_MATERIALS, t in TIMEPERIODS} INLET_FLOW_RATE[r,t,s]
;
problem PrimalSubproblem_FBL {s in SCENARIOS}:
	{r in RAW_MATERIALS, t in TIMEPERIODS} INLET[r,t,s],
	{m in MATERIALS, t in TIMEPERIODS} NODE[m,t,s],
	{(l0,l1) in LINKAGES, t in TIMEPERIODS} ARC[l0,l1,t,s],
	{t in TIMEPERIODS} PROFIT[t,s],
	{p in PRODUCTS, t in TIMEPERIODS} MIN_PRODUCTION_SL[p,t,s],
	{p in PRODUCTS, t in TIMEPERIODS} PROD_DEMAND_SL[p,t,s],
	{q in QUALITIES, p in PRODUCTS, t in TIMEPERIODS} QUALITY_BLENDING_RULE_MIN_SL[q,p,t,s],
	{q in QUALITIES, p in PRODUCTS, t in TIMEPERIODS} QUALITY_BLENDING_RULE_MAX_SL[q,p,t,s],
	FBL_OBJ_PrimalSubproblem[s],
	{r in RAW_MATERIALS, t in TIMEPERIODS} RAW_MAT_FLOW_RATE[r,t,s],
	{p in PRODUCTS, t in TIMEPERIODS} PROD_FLOW_RATE[p,t,s],
	{p in PRODUCTS, t in TIMEPERIODS} MIN_PRODUCTION_F[p,t,s],
	{p in PRODUCTS, t in TIMEPERIODS} PROD_DEMAND_F[p,t,s],
	{q in QUALITIES, p in PRODUCTS, t in TIMEPERIODS} QUALITY_BLENDING_RULE_MIN_F[q,p,t,s],
	{q in QUALITIES, p in PRODUCTS, t in TIMEPERIODS} QUALITY_BLENDING_RULE_MAX_F[q,p,t,s],
	{t in TIMEPERIODS} PROFIT_CALC[t,s],
	{r in RAW_MATERIALS, t in TIMEPERIODS} INLET_FLOW_RATE[r,t,s]
;
problem Master:
	{r in RAW_MATERIALS, t in TIMEPERIODS, s in SCENARIOS} INLET[r,t,s],
	eta,
	{s in SCENARIOS, ct in CUTS} GBD_F[s,ct],
	{r in RAW_MATERIALS, t in TIMEPERIODS, s in SCENARIOS, ct in CUTS} GBD_G_0[r,t,s,ct],
	MASTER_OBJ,
	{r in RAW_MATERIALS, t in TIMEPERIODS, s in SCENARIOS} NON_ANT[r,t,s],
	{ct in CUTS: is_feasible[ct] = 1} GBD_OPT_CUT[ct],
	{ct in CUTS: is_feasible[ct] = 0} GBD_FBL_CUT[ct]
;