option show_stats 3;
option conopt_options "outlev=3";
option knitro_options "outlev=3";
option cplex_options "outlev=2 mipdisplay=5";
option gurobi_options "outlev=1";

model refinery.mod;
data refinery.dat;

let S := 6;
let T := 10;

let {t in TIMEPERIODS: 5 <= t <= 6} SHUTDOWN['RF',t,1] := 1;
let {t in TIMEPERIODS: 4 <= t <= 7} SHUTDOWN['RF',t,2] := 1;
let {t in TIMEPERIODS: 3 <= t <= 8} SHUTDOWN['RF',t,3] := 1;
let {t in TIMEPERIODS: 5 <= t <= 6} SHUTDOWN['CC',t,4] := 1;
let {t in TIMEPERIODS: 4 <= t <= 7} SHUTDOWN['CC',t,5] := 1;
let {t in TIMEPERIODS: 3 <= t <= 8} SHUTDOWN['CC',t,6] := 1;

let {s in SCENARIOS} PROBABILITY[s] := 1/S;

CDU_SIZE: UNIT_SIZE['CDU'] = 500;
RF_SIZE: UNIT_SIZE['RF'] = 150;
CC_SIZE: UNIT_SIZE['CC'] = 150;

objective TOTAL_PROFIT;
option solver knitro;
solve;

display UNIT_SIZE;
display TANK_SIZE;
display TANK_LOCATION;
display TOTAL_PROFIT.val;