# Script Flags
# ----------------------------------------------------------------------------------------------------------------------
SPECIAL_COMMAND_MODEL = "MODEL"
SPECIAL_COMMAND_ADDITIONAL_MODEL = "ADDITIONAL_MODELS"
SPECIAL_COMMAND_INIT_DATA = "INIT_DATA"
SPECIAL_COMMAND_SETUP = "SETUP"
SPECIAL_COMMAND_NOEVAL = "NOEVAL"
SPECIAL_COMMAND_EVAL = "EVAL"
SPECIAL_COMMAND_OMIT_DECLARATIONS = "OMIT_DECL"
SPECIAL_COMMAND_INCLUDE_DECLARATIONS = "INCL_DECL"
SPECIAL_COMMAND_FSPROBLEM = "FSPROBLEM"
SPECIAL_COMMAND_SUBPROBLEM = "SUBPROBLEM"
SPECIAL_COMMAND_MASTER_PROBLEM = "MASTER_PROBLEM"
SPECIAL_COMMAND_PRIMAL_SUBPROBLEM = "PRIMAL_SUBPROBLEM"
SPECIAL_COMMAND_FEASIBILITY_SUBPROBLEM = "FEASIBILITY_SUBPROBLEM"
SPECIAL_COMMAND_INITIALIZATION = "INITIALIZATION"
SPECIAL_COMMAND_GBD_ALGORITHM = "GBD_ALGORITHM"
SPECIAL_COMMAND_OUTPUT = "OUTPUT"

SPECIAL_COMMAND_SYMBOLS = [SPECIAL_COMMAND_MODEL,
                           SPECIAL_COMMAND_ADDITIONAL_MODEL,
                           SPECIAL_COMMAND_INIT_DATA,
                           SPECIAL_COMMAND_SETUP,
                           SPECIAL_COMMAND_NOEVAL,
                           SPECIAL_COMMAND_EVAL,
                           SPECIAL_COMMAND_OMIT_DECLARATIONS,
                           SPECIAL_COMMAND_INCLUDE_DECLARATIONS,
                           SPECIAL_COMMAND_FSPROBLEM,
                           SPECIAL_COMMAND_SUBPROBLEM,
                           SPECIAL_COMMAND_MASTER_PROBLEM,
                           SPECIAL_COMMAND_PRIMAL_SUBPROBLEM,
                           SPECIAL_COMMAND_FEASIBILITY_SUBPROBLEM,
                           SPECIAL_COMMAND_INITIALIZATION,
                           SPECIAL_COMMAND_GBD_ALGORITHM,
                           SPECIAL_COMMAND_OUTPUT]